### ISSUE TITLE
Video downloading and preprocessing

### ISSUE THREAD

**Issue by izorin** [celebrity-audio-collection/videoprocess#26]
Dear Authors!

Thank you for your tremendous work and for making the pipeline available for other researchers! 
We'd like to reproduce this pipeline and implement it to gather datasets in other languages. As I understood there are no scripts for raw video collection and preprocessing to extract audio tracks from them. Could you please share the code. If not could you name tools you used to ease the process on our side. 

Thank you!

**Comment by chl17** [comment]
The videos used in collecting the published CN-Celeb dataset were manually downloaded at first, but we paid for a customized scraper (mainly for Chinese video websites) in order to collect videos automatically afterwards for producing an enlarged version. We understand the difficulties you might have encountered during collection of the videos, but unfortunately we cannot provide a web scraper at this point. As for the audio extraction, we simply use softwares like ffmpeg and sox.
